from . import approve_refuse_document
from . import create_document
from . import suspend_requirement
from . import upload_file
from . import refuse_requirement
from . import add_user_auth
from . import continue_requirement
from . import import_document
from . import update_partner_info
from . import web_import
from . import doc_add_area
from . import mail_compose_message