from . import poi_bizagi_import
from . import request_document
from . import request_document_approver
from . import document_system
from . import document
from . import document_auth_circuit
from . import document_log
from . import document_norm
from . import document_process
from . import document_template_circuit
from . import document_type
from . import document_user_approved
from . import request_doc_type
from . import request_doc_justification
from . import request_doc_complexity
from . import request_doc_priority
from . import document_sequence
from . import document_history
from . import document_tag
from . import document_mandatory_readers
from . import res_partner
from . import document_history_read
from . import ir_attachment
from . import document_stage
from . import mail_thread