# -*- encoding: utf-8 -*-
{
    'name': 'Scrum Viewer',
    'version': '1.0',
    'author': 'Alvaro Renato Paredes Flores, Jesus Gorostiaga',
    'website': 'https://www.poiesisconsulting.com',
    'summary': 'Vista Scrum Web',
    'depends': [
        'web',
        'base_setup',
        'bus',
        'website',
        'base',
        'project',
        'project_agile',
        'project_agile_scrum',
        'project_workflow_management',
        'hr_timesheet',
        'analytic',
    ],
    'description': """
""",
    "data": [
        'security/security.xml',
        "data/data.xml",
        'data/data_stages.xml',
        'data/data_cronjobs.xml',
        'views/menu.xml',
        "views/ticket_templates.xml",
        "views/project.xml",
        'views/project_stage_base_view.xml',
        'views/project_task_view.xml',
        'views/project_agile_team_view.xml',
        'views/project_agile_scrum_sprint_view.xml',
        'views/project_task_log_view.xml',
        'views/project_task_developing_view.xml',
        'views/project_priority_view.xml',
        'views/project_sponsor_view.xml',
        'views/project_origin_view.xml',
        'views/res_partner_view.xml',
        'views/ir_attachment_view.xml',
        'views/request_form_view.xml',
        'views/project_workflow_transition.xml',
        'report/general_schedule_view.xml',
        'report/developing_schedule_view.xml',
        'report/status_general_schedule.xml',
        'report/status_developing_schedule.xml',
        "data/ticket_security.xml",
        "data/data_request_form.xml",
        "security/ir.model.access.csv",
        'wizard/add_sprint_tasks_view.xml',
        'wizard/project_task_developing_wiz.xml',
        'wizard/project_sprint_wiz.xml',
        'wizard/add_task_link_wizard.xml',
        'wizard/pause_project.xml',
        'wizard/dismissed_project.xml',
        'wizard/task_add_user.xml',
    ],
    'qweb': [
        "static/src/xml/base.xml",
    ],
    'bootstrap': True,
    'installable': True,
    # 'application': True,
}

