{
    'name': "Modulo de Adecuaciones a Gestion de Documentos para BISA SEGUROS Y REASEGUROS S.A.",

    'summary': """
       Adecuaciones para el Módulos de Gestion Documental
    """,

    'author': "Alvaro Renato Paredes Flores",
    'website': "https://www.poiesisconsulting.com",

    'category': 'Document Management',
    'version': '12.0.1.1.0',

    # any module necessary for this one to work correctly
    'depends': [
        'muk_utils',
        'muk_autovacuum',
        'muk_dms',
        'muk_dms_access',
        'muk_dms_actions',
        'muk_dms_attachment',
        'muk_dms_field',
        'muk_dms_file',
        'muk_dms_lobject',
        'muk_dms_mail',
        'muk_dms_thumbnails',
        'muk_dms_view',
        'muk_fields_file',
        'muk_fields_lobject',
        'muk_hr_utils',
        'muk_quality_docs',
        'muk_quality_docs_dms',
        'muk_quality_docs_hr',
        'muk_security',
        'muk_web_client',
        'muk_web_client_refresh',
        'muk_web_preview',
        'muk_web_searchpanel',
        'muk_web_theme',
        'muk_web_theme_mail',
        'muk_web_utils',
        'poi_x_bisaseg',
    ],
    'data': [
        # 'security/security.xml',
        'security/access.xml',
        'data/data.xml',
        'data/data_stages.xml',
        # 'data/template_email.xml',
        'wizard/poi_bizagi_import.xml',
        'wizard/approve_refuse_document_view.xml',
        'wizard/create_document_view.xml',
        'wizard/suspend_requirement_view.xml',
        'wizard/continue_requirement_view.xml',
        'wizard/upload_file_view.xml',
        'wizard/refuse_requirement.xml',
        'wizard/add_user_auth_view.xml',
        'wizard/import_document_view.xml',
        'wizard/update_partner_info.xml',
        'wizard/doc_add_area_view.xml',
        'wizard/mail_compose_message.xml',
        'views/poi_bizagi_import.xml',
        'views/document_view.xml',
        'views/request_doc_view.xml',
        'views/request_document_approver_view.xml',
        'views/document_norm_view.xml',
        'views/document_tag_view.xml',
        'views/document_process_view.xml',
        'views/document_system.xml',
        'views/document_sequence.xml',
        'views/document_template_circuit_view.xml',
        'views/document_type_view.xml',
        'views/document_log_view.xml',
        'views/document_history_view.xml',
        'views/request_doc_complexity_view.xml',
        'views/request_doc_justification_view.xml',
        'views/request_doc_priority_view.xml',
        'views/request_doc_type_view.xml',
        'views/request_doc_type2_view.xml',
        'views/res_partner_view.xml',
        'views/document_stage.xml',
        'report/pending_approve_view.xml',
        'views/menu.xml',
        'security/ir.model.access.csv',
        "template/assets.xml",
    ],

    'demo': [
    ],

    # 'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': True,
    'application': False,
}
