# -*- coding: utf-8 -*-
from . import op_utility
from . import op_scholarship
from . import op_class
from . import op_course
from . import op_family
from . import op_family_tag
from . import op_matter
from . import op_matter_type
from . import op_parent
from . import op_profession
from . import op_relationship
from . import op_religion
from . import op_student
from . import op_student_case
from . import op_type
from . import op_teacher
from . import op_teacher_classification

from . import account_asset
from . import account_charge
from . import op_school_period
from . import product
from . import request_charge
from . import op_request_import
from . import account_payment
from . import res_partner
from . import account
from . import account_invoice
